# This application calculates the power for finding a correlation between two samples of equal size.
# The user selects the p values for the test by using the drop down widet. The slider allows the user to select varying sample size.
# The plot tab shows the power plot, and the table tab displays the data frame generated by the application that was used to draw the power plot. 
# The user input changes are reflected both in the plot and the table.
